# Generated by Django 4.0.4 on 2022-05-27 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ownerModel',
            fields=[
                ('owner_id', models.AutoField(primary_key=True, serialize=False)),
                ('owner_name', models.CharField(help_text='owner_name', max_length=50)),
                ('email', models.EmailField(help_text=' email', max_length=50)),
                ('password', models.CharField(help_text='password', max_length=50)),
                ('mobile', models.BigIntegerField(help_text='mobile')),
                ('location', models.CharField(help_text='location', max_length=200)),
                ('dob', models.DateField(help_text='dob')),
                ('owner_image', models.ImageField(upload_to='owner_image')),
                ('status', models.CharField(default='Pending', max_length=50, null='True')),
                ('otp', models.IntegerField(null=True)),
                ('reg_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'owner_details',
            },
        ),
    ]
