# Generated by Django 4.0.4 on 2022-05-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownerapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='fileModel',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('owner_id', models.IntegerField(null=True)),
                ('user_id', models.IntegerField(null=True)),
                ('file', models.FileField(upload_to='user_image/')),
                ('file_name', models.CharField(help_text='file_name', max_length=200)),
                ('description', models.CharField(help_text='description', max_length=250, null=True)),
                ('file_size', models.BigIntegerField(help_text='file_size', null=True)),
                ('file_type', models.CharField(help_text='file_type', max_length=300)),
                ('search_rank', models.CharField(default='0', max_length=200, null=True)),
                ('download_rank', models.CharField(default='0', max_length=250, null=True)),
                ('status', models.CharField(default='Pending', max_length=50, null='True')),
                ('file_uploaded_date', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'file_details',
            },
        ),
    ]
