# Generated by Django 4.0.4 on 2022-06-02 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownerapp', '0002_filemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='file_data',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='filemodel',
            name='file_key',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
