# Generated by Django 4.0.4 on 2022-06-03 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownerapp', '0003_filemodel_file_data_filemodel_file_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='otp',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='file',
            field=models.FileField(upload_to='files/'),
        ),
    ]
