# Generated by Django 4.0.4 on 2022-05-30 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_requestmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmodel',
            name='status',
            field=models.CharField(default='Forword', max_length=50, null='True'),
        ),
    ]
