# Generated by Django 4.0.4 on 2022-05-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_alter_requestmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmodel',
            name='status',
            field=models.CharField(default='Pending', max_length=50, null='True'),
        ),
    ]
