# Generated by Django 4.0.4 on 2022-05-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_alter_requestmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmodel',
            name='enclave_status',
            field=models.CharField(default='Pending', max_length=50, null='True'),
            preserve_default='True',
        ),
    ]
