# Generated by Django 4.0.4 on 2022-05-30 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_requestmodel_enclave_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestmodel',
            old_name='file_id',
            new_name='request_id',
        ),
    ]
