# Generated by Django 4.0.4 on 2022-05-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_rename_file_id_requestmodel_request_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmodel',
            name='file_id',
            field=models.IntegerField(null=True),
        ),
    ]
