# Generated by Django 4.0.4 on 2022-05-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_requestmodel_file_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestmodel',
            name='enclave_status',
        ),
        migrations.AddField(
            model_name='requestmodel',
            name='enclave',
            field=models.CharField(default='demo', max_length=50, null='True'),
            preserve_default='True',
        ),
    ]
