# Generated by Django 4.0.4 on 2022-05-31 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0009_remove_requestmodel_enclave_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestmodel',
            name='enclave',
        ),
        migrations.AddField(
            model_name='requestmodel',
            name='enclave_status',
            field=models.CharField(default='Pending', max_length=50, null='True'),
            preserve_default='True',
        ),
    ]
