# Generated by Django 4.0.4 on 2022-05-31 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0010_remove_requestmodel_enclave_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmodel',
            name='otp',
            field=models.IntegerField(null=True),
        ),
    ]
