# Generated by Django 4.0.4 on 2022-05-31 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0011_requestmodel_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='otpModel',
            fields=[
                ('otp_id', models.AutoField(primary_key=True, serialize=False)),
                ('owner_id', models.IntegerField(null=True)),
                ('file_id', models.IntegerField(null=True)),
                ('user_id', models.IntegerField(null=True)),
                ('request_id', models.IntegerField(null=True)),
                ('file', models.FileField(upload_to='user_image/')),
                ('file_name', models.CharField(help_text='file_name', max_length=200)),
                ('description', models.CharField(help_text='description', max_length=250, null=True)),
                ('file_size', models.BigIntegerField(help_text='file_size', null=True)),
                ('file_type', models.CharField(help_text='file_type', max_length=300)),
                ('otp', models.IntegerField(null=True)),
                ('status', models.CharField(default='Pending', max_length=50, null='True')),
                ('enclave_status', models.CharField(default='Pending', max_length=50, null='True')),
                ('requested_date', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'request_otp_details',
            },
        ),
    ]
