# Generated by Django 4.0.4 on 2022-05-31 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0012_otpmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestmodel',
            name='otp',
        ),
    ]
