# Generated by Django 4.0.4 on 2022-06-01 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0013_remove_requestmodel_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmodel',
            name='send_key',
            field=models.CharField(default='Pending', max_length=50, null='True'),
            preserve_default='True',
        ),
    ]
