# Generated by Django 4.0.4 on 2022-06-01 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0014_requestmodel_send_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestmodel',
            old_name='send_key',
            new_name='key_status',
        ),
    ]
