# Generated by Django 4.0.4 on 2022-06-01 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0016_requestmodel_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestmodel',
            name='key',
        ),
    ]
