# Generated by Django 4.0.4 on 2022-06-03 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0019_remove_requestmodel_otp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='otpModel',
        ),
    ]
