# Generated by Django 4.0.4 on 2022-06-03 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0020_delete_otpmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='verification',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
